id = "dang"
name = "Dang"
version = "0.1.1"
schema_version = 1
description = "Dang language support for Zed"
authors = ["vito"]
repository = "https://github.com/vito/dang"

[grammars.dang]
repository = "https://github.com/vito/dang"
commit = "c57b3138dea47cf57cec89179eb3f879527b878b"
path = "treesitter"

[language_servers.dang-lsp]
name = "Dang LSP"
languages = ["Dang"]
